### ISSUE TITLE
Issues with the package setup/installation

### ISSUE THREAD

**Issue by sanjaybharadwaj** [Pelagicore/common-api-cmdline#1]
Hi Team,

I tried to install the package as mentioned in the readme file,
during the installation I get the following error.

FATAL ERROR
[INFO] Error building POM (may not be this project's POM).
Project ID: org.genivi.commonapi:codegen
Reason: Cannot find layout implementation corresponding to: 'p2' for remote repository with id: 'kepler'. for project org.genivi.commonapi:codegen

Please let me know if you know this error already and have a solution for the same.
Also could you please let me know if there is a document/guide to run the SOMEIP test program running.

Thanks and regards,
Sanjay Bharadwaj

**Comment by jacky405** [comment]
Hello,

I am not sure which readme file you are referring to, since the one here does not indicate any instruction for building the package (which is obviously a bad thing).
The project can be built with the following steps:
   $ cmake .
   $ make -DCMAKE_INSTALL_PREFIX=/My/Installation/Path
   $ make install

Please let me know if it works for you.

**Comment by sanjaybharadwaj** [comment]
Hi Jacky,

Thanks for quick reply.
cmake part of the commands are fine but when I try make install I am getting the error again.
Make install triggers the generation of launcher_maven

It again outputs the  following:
Project ID: org.genivi.commonapi:codegen
Reason: Cannot find layout implementation corresponding to: 'p2' for remote repository with id: 'kepler'. for project org.genivi.commonapi:codegen

The readme file I am referring to has the following steps (This is present as a pre-requisit for running SOMEIP test program)
http://git.projects.genivi.org/?p=someip.git;a=blob;f=INSTALL.md;

Download and install the "common-api-cmdline" package, which contains the runtime needed for commonAPI command-line generators.

$git clone https://github.com/Pelagicore/common-api-cmdline.git
$cd common-api-cmdline
$cmake -DCMAKE_INSTALL_PREFIX=/My/Installation/Location
$make install

Please help me solve the error, 
Thank you.

**Comment by jacky405** [comment]
Maybe your version of Maven is incorrect ?
The version I am using here is 3.0.5

**Comment by sanjaybharadwaj** [comment]
Thank you for helping me out
The error was solved :)

The problem and soln is as follows:
1. Only Maven needs to be installed on Ubuntu (There exist Maven2 also, installing this or both might not work)
2. I was using proxy only for http server, but the maven downloads files via ftp also, even this had to be added to the proxy list.
